# Introdução ao NumPy

O NumPy é uma biblioteca para a linguagem de programação Python, que dá suporte à grandes matrizes e arrays multidimensionais, juntamente com uma grande coleção de funções matemáticas de alto nível para operar nesses arrays.

A principal vantagem do NumPy é a sua incrível eficiência. Ele foi implementado em C e Fortran, o que significa que as operações de matrizes executadas em código compilado nativo são muito rápidas. Além disso, a biblioteca usa uma estrutura de dados especial chamada array n-dimensional, que permite armazenar dados de forma mais eficiente do que as listas nativas do Python.

Os arrays NumPy são usados como os principais contêineres de dados em muitas outras bibliotecas científicas e de análise de dados, incluindo pandas, SciPy, scikit-learn e outros. Eles também são extremamente úteis para a manipulação de dados em qualquer tipo de cálculo numérico, análise estatística, processamento de imagem, entre outros.

## Instalação

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


## Importação

In [2]:
import numpy as np

## Criando Arrays

### Criando arrays a partir de uma lista

In [3]:
my_array = np.array([1, 2, 3, 4])
print(my_array)

[1 2 3 4]


### Criando um array multidimensional

In [4]:
my_2d_array = np.array([[1, 2], [3, 4]])
print(my_2d_array)

[[1 2]
 [3 4]]


### Criando um array de zeros

In [5]:
zeros_array = np.zeros((3, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Criando um array de uns

In [6]:
ones_array = np.ones((2, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


### Criando um array com uma sequência regular

In [8]:
# A função np.arange permite criar um array com uma sequência de números
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


### Criando um array com valores espaçados uniformemente

In [9]:
linspace_array = np.linspace(0, 1, 5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


#### Criando um array preenchidos com valores especificados

In [10]:
full_array = np.full((3, 3), 7)
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Criando um array com forma pré-definida e valores aleatórios 

In [11]:
random_array = np.random.rand(2, 2)
print(random_array)

[[0.29786382 0.14334902]
 [0.3392623  0.42831597]]


### Criando uma matriz identidade

In [12]:
eye_array = np.eye(3)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Salvando e Carregando do Disco

### `np.save(file, arr)`

In [13]:
my_array = np.array([1, 2, 3, 4])
np.save('my_array.npy', my_array)

### `np.load(file, mmap_mode=None)`

`file`: O nome do arquivo ou objeto de arquivo de onde o array será carregado.

`mmap_mode`: (Opcional) Modo de mapeamento de memória. Se fornecido, retorna um array de mapeamento de memória, que permite que você acesse uma parte do array sem ler todo o conteúdo na memória. Isso pode ser útil para trabalhar com arquivos grandes.

In [ ]:
loaded_array = np.load('my_array.npy')
print(loaded_array)

## Criando dados sintéticos

### Dados uniformemente distribuídos

> Dados aleatórios uniformemente distribuídos referem-se a um tipo de distribuição estatística onde todos os valores dentro de um determinado intervalo têm a mesma probabilidade de ocorrência. Essa distribuição é chamada de "uniforme" porque a probabilidade é constante (ou uniforme) em todo o intervalo.

In [15]:
uniform_data = np.random.rand(10, 2)
uniform_data

array([[0.85685587, 0.34358698],
       [0.89472916, 0.96661535],
       [0.41512817, 0.46148622],
       [0.49555072, 0.43109779],
       [0.33428878, 0.88857618],
       [0.73683168, 0.5377658 ],
       [0.28772496, 0.87156583],
       [0.30819727, 0.29891943],
       [0.6400373 , 0.48753294],
       [0.53844786, 0.40218687]])

### Dados normalmente distribuídos

In [17]:
normal_data = np.random.randn(10, 2)
normal_data

array([[-0.07947299, -0.35492598],
       [-2.76106663,  1.43719591],
       [-0.76353747, -0.79227878],
       [ 0.54760708, -1.13050084],
       [-0.04962951,  0.98913909],
       [ 1.37169868, -1.1023145 ],
       [ 1.02399121,  0.94837995],
       [-0.20882218, -1.53847689],
       [-0.23571682,  0.59126701],
       [ 1.10694331, -0.58585477]])

### Dados de distribuição específica

In [18]:
binomial_data = np.random.binomial(n=10, p=0.5, size=100)
binomial_data

array([7, 6, 2, 4, 5, 5, 5, 7, 3, 5, 3, 7, 4, 6, 5, 3, 7, 4, 6, 4, 3, 6,
       4, 4, 5, 4, 5, 7, 4, 3, 7, 3, 5, 5, 6, 8, 2, 6, 4, 4, 6, 2, 8, 5,
       7, 3, 7, 3, 7, 2, 4, 4, 4, 4, 4, 6, 5, 4, 5, 7, 2, 5, 3, 6, 6, 7,
       6, 4, 7, 5, 4, 7, 3, 5, 5, 2, 4, 3, 4, 7, 4, 4, 5, 8, 6, 7, 6, 8,
       7, 6, 6, 3, 5, 6, 4, 4, 6, 6, 4, 3])

### Simulação de Séries Temporais

O NumPy pode ser usado para simular séries temporais ou processos estocásticos. Por exemplo, uma caminhada aleatória.

In [22]:
walk = np.random.choice([-1, 1], size=10)
print(walk)
cum_walk = np.cumsum(walk)
print(cum_walk)

[ 1  1  1 -1 -1  1 -1  1 -1  1]
[1 2 3 2 1 2 1 2 1 2]


#### Dados Estruturados

In [25]:
names = ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
ages = [25, 30, 22, 35, 40]

structured_data = np.array(list(zip(names, ages)), dtype=[('name', 'U10'), ('age', 'i4')])
structured_data

array([('Alice', 25), ('Bob', 30), ('Charlie', 22), ('David', 35),
       ('Eva', 40)], dtype=[('name', '<U10'), ('age', '<i4')])